### ISSUE TITLE
Occurs a build error related to file configuration 

### ISSUE THREAD

**Issue by superbderrick** [hankyojeong/iOS_AudioToolbox_Sample#1]

**Comment by superbderrick** [comment]
Hey mate, I tried to build your sample projects but it could not execute. I assume that it seem to be built file configurations for only your computer , could you check file configurations  (mp4 and caf) in your sample projects? thanks in advance

**Comment by superbderrick** [comment]
FYI the build errors..... 
 /Users/derrick/restart/iOS_AudioToolbox_Sample/AudioSampleCode/AVAudioEngineSample/Swift/AVAudioEngineSample/AVAudioEngineSample/SimpsonMovie.mp4 /Users/derrick/Library/Developer/Xcode/DerivedData/AVAudioEngineSample-dmpomhqanmzuzfafscoqihebqfgo/Build/Products/Debug-iphonesimulator/AVAudioEngineSample.app/SimpsonMovie.mp4 (in target 'AVAudioEngineSample' from project 'AVAudioEngineSample')
    cd /Users/derrick/restart/iOS_AudioToolbox_Sample/AudioSampleCode/AVAudioEngineSample/Swift/AVAudioEngineSample
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/derrick/restart/iOS_AudioToolbox_Sample/AudioSampleCode/AVAudioEngineSample/Swift/AVAudioEngineSample/AVAudioEngineSample/SimpsonMovie.mp4 /Users/derrick/Library/Developer/Xcode/DerivedData/AVAudioEngineSample-dmpomhqanmzuzfafscoqihebqfgo/Build/Products/Debug-iphonesimulator/AVAudioEngineSample.app

error: /Users/derrick/restart/iOS_AudioToolbox_Sample/AudioSampleCode/AVAudioEngineSample/Swift/AVAudioEngineSample/AVAudioEngineSample/SimpsonMovie.mp4: No such file or directory (in target 'AVAudioEngineSample' from project 'AVAudioEngineSample')

**Comment by DevCoop-code** [comment]
Hello @superbderrick 
There is no SimpsonMovie.mp4 in these repository
you should put your own video or audio
and then put your video file name & extension
Below is the code what you should put your video file name & extension in ViewController.swift
audioFileURL = Bundle.main.url(forResource: "SimpsonMovie", withExtension: "mp4")

Thank you for feedback

**Comment by superbderrick** [comment]
Thanks quickly reply, it would be good to put the above information in readme.md :)

**Comment by DevCoop-code** [comment]
Sounds wonderful
i will do that
Thanks @superbderrick

**Comment by superbderrick** [comment]
request for that https://github.com/hankyojeong/iOS_AudioToolbox_Sample/pull/2#issue-356893034
